
file =  ( comment | <WS+>| <eol+> |kv)+

comment = start-comment <WS?> inside-comment? <eol>

kv = (<WS*> key <WS*> '=' <WS*> (hash | value) <WS*> <eol?> | comment )
hash = "{" ( kv | comment)* "}"

key = #"[a-zA-Z0-9\_\-]+"
value = <'"'?> #"[a-zA-Z0-9\_\-\.]+" <'"'?>


WS = #'\s+'
eol = #'[\n|\r]+'

<STRING> = #"[^\s][a-zA-Z\ \t]*"
S = start-comment inside-comment? end-comment
start-comment = '#'
inside-comment = #'.+'
end-comment = '\n' | '\r?\n'