
file =  ( comment | <ws>| <ows> | kv |key)+

comment = start-comment <ws?> inside-comment? <eol>

kv = (<ows> key <ows> separator <ows> (hash | value ) <ows> <eol?> | comment )
hash = "{" <ows>( kv| key | comment | <ows> )+ <ows> "}"


key = <'"'?> #"[a-zA-Z0-9\_\-]+" <'"'?>
separator = "=" | ">" | "<" | ">=" | "<="
value = <'"'?> #"[a-zA-Z0-9\_\-\.\@]+" <'"'?>


ws = #'(\s|\n|\r|\t| )+'
ows = #'\s*'
eol = #'[\n\r]+'

<STRING> = #"[^\s][a-zA-Z\ \t]*"
S = start-comment inside-comment? end-comment
start-comment = '#'
inside-comment = #'.+'
end-comment = '\n' | '\r?\n'
